# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08b82c669747c91488330f61f6ae0de538a2aeca0df7e5ac41f5c95e0978dd44c8d93f8d5eb3d6fa0d4e4395ff531c38017c10d7a4bd7909b526f4653bf277c6

test:
  secret_key_base: 44b71e818f937503b5d367042149c9107dbca025c0cfe78db3d89de0a2f85a1ca725a8101d4719748045fbe38914ad14ee5e43a52da961f2f52976d66c62970a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
